# Generated by Django 6.0.4 on 2026-04-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentprofile_phone_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_total_due', models.DecimalField(decimal_places=2, default=960.0, max_digits=10)),
            ],
        ),
    ]
