# Generated by Django 6.0.4 on 2026-04-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
