# Generated by Django 6.0.4 on 2026-04-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentprofile_raw_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='contact_email',
            field=models.EmailField(default='contact@befree.fr', max_length=254),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='contact_phone',
            field=models.CharField(default='+33 1 23 45 67 89', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='site_name',
            field=models.CharField(default='Be-Free E-commerce', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
