# Generated by Django 6.0.4 on 2026-04-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_platformsettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='payment_status',
            field=models.CharField(choices=[('OK', 'Réglé'), ('missed', 'En attente'), ('overdue', 'En retard')], default='OK', max_length=20),
        ),
    ]
