# Generated by Django 6.0.4 on 2026-04-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_studentprofile_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
