# Generated by Django 6.0.4 on 2026-04-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_platformsettings_stripe_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_mode',
            field=models.CharField(choices=[('test', 'Sandbox (Test)'), ('live', 'Production (Live)')], default='test', max_length=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_public_key_live',
            field=models.CharField(blank=True, help_text='Clé publique Stripe LIVE (pk_live_...)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_secret_key_live',
            field=models.CharField(blank=True, help_text='Clé secrète Stripe LIVE (sk_live_...)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_webhook_secret_live',
            field=models.CharField(blank=True, help_text='Secret Webhook Stripe LIVE (whsec_...)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='stripe_public_key',
            field=models.CharField(blank=True, help_text='Clé publique Stripe TEST (pk_test_...)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, help_text='Clé secrète Stripe TEST (sk_test_...)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, help_text='Secret Webhook Stripe TEST (whsec_...)', max_length=255, null=True),
        ),
    ]
