# Generated by Django 6.0.4 on 2026-05-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_platformsettings_stripe_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='default_from_email',
            field=models.CharField(blank=True, help_text='Ex: Be-Free <no-reply@befree.fr>', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_host',
            field=models.CharField(blank=True, help_text='Ex: smtp.gmail.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Mot de passe ou App Password Google', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text="Adresse e-mail d'expédition", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_port',
            field=models.PositiveIntegerField(blank=True, help_text='Ex: 587', null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_use_tls',
            field=models.BooleanField(blank=True, help_text='Activer TLS (recommandé)', null=True),
        ),
    ]
