# Generated by Django 6.0.4 on 2026-05-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_platformsettings_default_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='kbis_file',
            field=models.FileField(blank=True, null=True, upload_to='kbis/'),
        ),
    ]
