# Generated by Django 6.0.4 on 2026-05-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
