# Generated by Django 6.0.4 on 2026-05-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_studentprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='formation_type',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='preferred_schedule',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_offer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='has_business',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='monthly_revenue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
