# Generated by Django 6.0.4 on 2026-05-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_studentprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='default_due_date',
            field=models.DateField(blank=True, help_text='Date d’échéance globale par défaut pour tous les clients', null=True),
        ),
    ]
